// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $PressureDisplay from "./islands/PressureDisplay.tsx";
import * as $WeatherIcon from "./islands/WeatherIcon.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/PressureDisplay.tsx": $PressureDisplay,
    "./islands/WeatherIcon.tsx": $WeatherIcon,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
